name: "Tommy's Tester"
favicon: null
layout_spectrum: 0.1255000822711736
typography_spectrum: 0.30485415924340487
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#afc2d3'
    - '#ebece7'
    - '#0c1622'
    - '#7b8093'
    - '#555657'
  brandStrength: 0.3779222897719592
  lightness: 0.7153518961276859
  saturation: 0.6464069199282676
  rhythmicContrast: 0.7355040395632386
purpose: []
